name: Build Python

on: 
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
  
jobs:
  build:
    uses: asbaba-corp/pipelines/.github/workflows/pr-check-python.yml@main
    secrets: inherit    
        
 
