name: Build Python

on: 
  #pull_request:
  issue_comment:
    types: [created]
  
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Github API Request
      id: request
      uses: octokit/request-action@v2.0.0
      with:
        route: ${{ github.event.issue.pull_request.url }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Execute for pull request comments only
      if: github.event.issue.pull_request
      run: echo "This is a pull request comment event"

      
#    if: ${{ always() || (github.event.issue.pull_request && github.event.issue.comment.body == '/check') }}
#    uses: asbaba-corp/pipelines/.github/workflows/pr-check-python.yml@main
#    secrets: inherit    
