name: Release Dev Workflow

on:
  push:
    branches:
      - main

jobs:
    check:
      uses: asbaba-corp/pipelines/.github/workflows/release-dev.yml@main
      with:
        repository_language: "python"
        config_directory: .
        module: "auth"
      secrets: inherit   
